[package]
name = "filamentseek-model"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
surreal_socket = { path = "../surrealsocket" }
serde = "1.0.219"
serde_json = "1.0.143"
utoipa = "5.4.0"
surrealdb = "2.2.1"
